spring:
  jpa:
    hibernate:
      ddl-auto: none

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_todolist
    username: root
    password: 123456

  flyway:
    table: flyway_schema_history
    baseline-on-migrate: true