version: '3.6'
    
services: 
    # MySQL
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_DATABASE: mydb
            MYSQL_USER: todouser
            MYSQL_PASSWORD: 123456

        volumes: 
            - ./init:/docker-entrypoint-initdb.d
        ports:
            - 3306:3306
